services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql+asyncpg://keystone:keystone@db:5432/keystone
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=keystone
      - POSTGRES_PASSWORD=keystone
      - POSTGRES_DB=keystone

volumes:
  postgres_data:
