"""Update models with user and invitation changes

Revision ID: 067c920e7b56
Revises: 82689c25b22f
Create Date: 2025-09-20 12:53:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '067c920e7b56'
down_revision = '82689c25b22f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('token', sa.String(), nullable=False))
    op.create_index(op.f('ix_invitations_token'), 'invitations', ['token'], unique=True)
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_invitations_token'), table_name='invitations')
    op.drop_column('invitations', 'token')
    # ### end Alembic commands ###
