name: Keystone CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Start services
        run: docker compose up -d --build

      - name: Wait for database to be ready
        run: |
          until docker compose exec -T db pg_isready --username=keystone; do
            sleep 1
          done

      - name: Run database migrations
        run: docker compose exec -T api poetry run alembic upgrade head

      - name: Run tests
        run: docker compose exec -T api poetry run pytest

      - name: Stop services
        if: always()
        run: docker compose down
